development:
  DB_NAME: 'ajackus_development'
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_HOST: 'localhost'
  DB_PORT: '5432'

  HOST: 'localhost:3000'
  REDIS_URL: 'redis://localhost:6379'

  EMAIL_RECEIVER: info@ajackus.com

production:
  DB_NAME: ''
  DB_USERNAME: ''
  DB_PASSWORD: ''
  DB_HOST: ''
  DB_PORT: ''

  HOST: ''
  REDIS_URL: ''

  EMAIL_RECEIVER: ''

test:
  DB_NAME: 'ajackus_test'
  DB_USERNAME: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_HOST: 'localhost'
  DB_PORT: '5432'

  HOST: ''
  REDIS_URL: ''

  EMAIL_RECEIVER: ''
